### ISSUE TITLE
Quick-mining glitch/potential oversight

### ISSUE THREAD

**Issue by Tiger-Tom** [RobertElderSoftware/robert-elder-software-java-modules#1]
> This is my favorite potential bug

Holding down the "M" (mine) key results in a rapid obtaining of material, which may not be intended. Perhaps a delay, or a requirement to release the key, would make the game more challenging?

**Comment by Tiger-Tom** [comment]
> This was my favorite new thing that I learned today
I learned something new today! I shouldn't be surprised, though, given your videos...
Anyway, I'm proud to be among the first to play this game. As for launching, I used the precompiled .JAr file, and launched it with `/usr/lib/jvm/java-21-openjdk/bin/java -jar block-manager-single-player-client-0.0.1.jar`, and figured out that I had to download the `v1_block_schema.json` (I probably didn't read the directions very closely). 
As for the game itself, it does seem to start slowing down generation-wise after a little while, with a lot of `?` that don't go away for a long time. The gameplay itself is fun, but it's hard to see where I can go down or up `Y`-wise. So far I've only found `Rock` and (more recently) `WoodenBlock`, but I'm happy to see from the screenshot on the main page that `Ilmenite` made it into the game!
I do have one question though: what is the difference between `?` and `U`?

**Comment by RobertElder** [comment]
Ah yes, I should probably document the significance of 'v1_block_schema.json' a bit better.  The long-term vision would be to externalize how the game world looks inside a 'block schema' file so that different versions of the game could interact with each other.  From your other repos, I can see that you are familiar with the NBT tag structure of minecraft.   The storage/representation system that I imagine creating is one like the early apha edition of Minecraft, but to a more extreme extent.  The most portable game representation would be one where blocks are fairly 'de-normalized' and self-contained.  Generally speaking, it would be possible to have multiple entirely different game clients that can interact in a shared game universe by simply interpreting the blocks in a different way.  Having said this, my ideas are not fully fleshed out yet, and I may yet have to make backward-incompatible changes in the future.

The meaning of the '?' is a block for which information has not yet been obtained from the server (although it's local single player only, you'll see in the game files that it's separated into a client/server architecture).  The meaning of 'U' means that a request came back from the server, but there is no information about the block at that location, so it is '**Uninitialized**'.  When the block gets initialized, an update will be sent to the client.

Yes, there is definitely a usability issue with being able to see where you can go up/down in the Y direction.  I'll add that to the todo pile.   I am pleased to hear you describe it as 'fun'.  Most of the work went into building all chunk/block/initialization systems from scratch.  I've spent almost no time on game mechanics yet, and I just made up a couple crafting rules to say that I actually have them.  The fact that you see '?' that don't go away after a while is a bit odd.  Those would be pending requests to the chunk server.  It might also be due to pending slow database reads on the chunk server.  The entire block world is stored in a SQLite database.  I don't know how well that's going to scale as the world gets bigger, but I guess we'll find out.  The server also has a design flaw where it registers an unbounded number of 'subscriptions' to notify the client about updates in that region.  It's not really a feature that's used much at the moment, but it's another todo to fix for a future version.

If you want to find more examples of ore blocks in the game, you should be able to travel to X=114, Y=-1, Z=44 and find a bunch.  Currently, everyone (I expect) has the same deterministic game world with a fixed seed.  It's all generated using a from-scratch noise function generator that I wrote which uses a gradient interpolation method, just like with Perlin noise, although in my case it uses a SHA512 of the coordinates instead of a lookup table.
